version: '3.3'

services:
  db:
    container_name: elevnn-staging-db
    image: mysql:5.7
    env_file: wordpress.env
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - webproxy

  wordpress:
    container_name: elevnn-staging-wp
    build:
      context: ./config/images/
      dockerfile: Dockerfile-wp-git
    depends_on:
      - db
    image: wordpress:latest
    env_file: wordpress.env
    ports:
      - "8080:80"
    expose:
      - "8080"
    restart: unless-stopped
    volumes:
      - ./public:/var/www/html
    environment:
      - VIRTUAL_HOST=staging.elevnn.com
    networks:
      - webproxy

  wordmove:
    env_file: 
      - wordpress.env
      - movefile.secrets.env
    tty: true
    depends_on:
      - db
      - wordpress
    image: welaika/wordmove
    restart: unless-stopped
    container_name: elevnn_wordmove
    volumes:
      - ./movefile.yml:/home/movefile.yml
      - ./public:/var/www/html/
    networks:
      - webproxy

volumes:
    db_data: {}

networks:
  webproxy: