version: '3.3'

services:
   db:
     image: mysql:5.7
     env_file: wordpress.env
     volumes:
       - db_data:/var/lib/mysql
     restart: always

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     env_file: wordpress.env
     ports:
       - "9000:80"
     restart: always
     volumes:
       - ./wp-content:/var/www/html/wp-content
volumes:
    db_data: {}
