version: '3.3'

services:
  wordpress:
    environment:
      - WP_DEBUG=true
      - WORDPRESS_DEBUG=true

  phpmyadmin:
    depends_on: 
      - db
    image: phpmyadmin/phpmyadmin
    env_file: wordpress.env
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: unless-stopped
    ports:
      - 8090:80
    volumes:
      - /sessions
    networks:
      - webproxy
